# Generated by Django 4.2.30 on 2026-07-20 01:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nom de la catégorie')),
                ('slug', models.SlugField(unique=True, verbose_name="Slug d'URL")),
                ('description', models.TextField(blank=True, verbose_name='Description de la catégorie')),
                ('icon_name', models.CharField(blank=True, max_length=50, verbose_name="Nom de l'icône Lucide")),
                ('store_type', models.CharField(choices=[('COSMETIC', 'Cosmétique'), ('CLOTHING', 'Prêt-à-porter')], default='COSMETIC', max_length=20, verbose_name='Type de boutique associé')),
            ],
            options={
                'verbose_name': 'Catégorie',
                'verbose_name_plural': 'Catégories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ClothingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom de la création')),
                ('slug', models.SlugField(unique=True, verbose_name="Slug d'URL")),
                ('description', models.TextField(verbose_name='Description de la coupe et tissus')),
                ('price_fcfa', models.PositiveIntegerField(verbose_name="Prix d'atelier en FCFA")),
                ('image_url', models.URLField(max_length=500, verbose_name="URL de l'image éditoriale")),
                ('is_new', models.BooleanField(default=False, verbose_name='Marquer comme pièce récente')),
                ('stock_xs', models.PositiveIntegerField(default=5, verbose_name='Stock Taille XS')),
                ('stock_s', models.PositiveIntegerField(default=10, verbose_name='Stock Taille S')),
                ('stock_m', models.PositiveIntegerField(default=10, verbose_name='Stock Taille M')),
                ('stock_l', models.PositiveIntegerField(default=5, verbose_name='Stock Taille L')),
                ('stock_xl', models.PositiveIntegerField(default=3, verbose_name='Stock Taille XL')),
                ('category', models.ForeignKey(limit_choices_to={'store_type': 'CLOTHING'}, on_delete=django.db.models.deletion.PROTECT, related_name='clothes', to='core.category', verbose_name='Catégorie Mode')),
            ],
            options={
                'verbose_name': 'Création Mode',
                'verbose_name_plural': 'Créations Mode',
                'ordering': ['-is_new', 'name'],
            },
        ),
        migrations.CreateModel(
            name='CosmeticProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nom du soin')),
                ('slug', models.SlugField(unique=True, verbose_name="Slug d'URL")),
                ('description', models.TextField(verbose_name="Description de l'onguent ou soin")),
                ('price_fcfa', models.PositiveIntegerField(verbose_name='Prix en FCFA')),
                ('image_url', models.URLField(max_length=500, verbose_name="URL de l'image de présentation (Unsplash/CDN)")),
                ('is_new', models.BooleanField(default=False, verbose_name='Marquer comme nouveauté')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)], verbose_name='Note moyenne sur 5')),
                ('stock_quantity', models.PositiveIntegerField(default=50, verbose_name='Quantité disponible')),
                ('category', models.ForeignKey(limit_choices_to={'store_type': 'COSMETIC'}, on_delete=django.db.models.deletion.PROTECT, related_name='cosmetics', to='core.category', verbose_name='Catégorie')),
            ],
            options={
                'verbose_name': 'Produit Cosmétique',
                'verbose_name_plural': 'Produits Cosmétiques',
                'ordering': ['-is_new', '-rating'],
            },
        ),
        migrations.CreateModel(
            name='FacebookConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_id', models.CharField(max_length=100, verbose_name='ID de Page Facebook')),
                ('access_token', models.CharField(max_length=255, verbose_name='Token Graph API')),
                ('cache_ttl_minutes', models.PositiveIntegerField(default=60, verbose_name='Durée de cache (minutes)')),
            ],
            options={
                'verbose_name': 'Configuration Facebook',
                'verbose_name_plural': 'Configurations Facebook',
            },
        ),
        migrations.CreateModel(
            name='GuestSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name="Prénom de l'invitée")),
                ('phone_number', models.CharField(max_length=20, verbose_name='Téléphone de facturation MoMo')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email de contact (facultatif)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'enregistrement")),
            ],
            options={
                'verbose_name': 'Session Invitée',
                'verbose_name_plural': 'Sessions Invitées',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount_fcfa', models.PositiveIntegerField(verbose_name='Montant total en FCFA')),
                ('status', models.CharField(choices=[('PENDING', 'En attente de règlement'), ('PAID', 'Payé — En cours de préparation'), ('SHIPPED', 'Colis Expédié'), ('DELIVERED', 'Livré à Domicile'), ('CANCELLED', 'Annulé')], default='PENDING', max_length=20, verbose_name='Statut Logistique')),
                ('delivery_address', models.TextField(verbose_name='Adresse ou point de livraison au Cameroun')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Date d'achat")),
                ('guest', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.guestsession', verbose_name='Invitée')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Membre')),
            ],
            options={
                'verbose_name': 'Commande',
                'verbose_name_plural': 'Commandes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=20, verbose_name='Numéro de téléphone Mobile Money (+237)')),
                ('receive_newsletters', models.BooleanField(default=True, verbose_name="S'abonner aux newsletters de luxe")),
                ('loyalty_points', models.PositiveIntegerField(default=0, verbose_name='Points privilèges cumulés')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Cliente',
                'verbose_name_plural': 'Profils Clientes',
            },
        ),
        migrations.CreateModel(
            name='PaymentTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('ORANGE', 'Orange Money')], max_length=15, verbose_name='Opérateur')),
                ('payment_mode', models.CharField(choices=[('MERCHANT', 'Code Marchand Officiel'), ('DIRECT_DEPOSIT', 'Dépôt vers Compte Particulier')], default='MERCHANT', max_length=20, verbose_name='Mode de réception du paiement')),
                ('amount_fcfa', models.PositiveIntegerField(verbose_name='Somme payée en FCFA')),
                ('phone_debited', models.CharField(max_length=20, verbose_name='Numéro MoMo débité')),
                ('ussd_string_dialed', models.CharField(max_length=100, verbose_name='Ligne USSD composée')),
                ('transaction_id', models.CharField(max_length=100, unique=True, verbose_name='ID Transaction Opérateur')),
                ('is_verified', models.BooleanField(default=False, verbose_name="Transaction vérifiée par l'administrateur")),
                ('verified_at', models.DateTimeField(blank=True, null=True, verbose_name='Date de validation manuelle')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment', to='core.order')),
            ],
            options={
                'verbose_name': 'Transaction Mobile Money',
                'verbose_name_plural': 'Transactions Mobile Money',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_size', models.CharField(blank=True, max_length=10, verbose_name='Taille sélectionnée')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantité')),
                ('price_fcfa', models.PositiveIntegerField(verbose_name='Prix unitaire en FCFA')),
                ('clothing_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.clothingproduct', verbose_name='Création Mode')),
                ('cosmetic_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.cosmeticproduct', verbose_name='Produit Cosmétique')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.order', verbose_name='Commande')),
            ],
            options={
                'verbose_name': 'Article de commande',
                'verbose_name_plural': 'Articles de commande',
            },
        ),
        migrations.CreateModel(
            name='FavoriteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='Ajouté le')),
                ('clothing_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.clothingproduct', verbose_name='Création Mode')),
                ('cosmetic_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='core.cosmeticproduct', verbose_name='Produit Cosmétique')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='Cliente')),
            ],
            options={
                'verbose_name': 'Article Favori',
                'verbose_name_plural': 'Articles Favoris',
                'unique_together': {('user', 'clothing_product'), ('user', 'cosmetic_product')},
            },
        ),
    ]
