# Generated by Django 4.2.30 on 2026-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clothingproduct',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name="Image uploadée (prioritaire sur l'URL CDN)"),
        ),
        migrations.AddField(
            model_name='clothingproduct',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/', verbose_name='Vidéo produit (MP4/WebM recommandé)'),
        ),
        migrations.AddField(
            model_name='cosmeticproduct',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to='products/images/', verbose_name="Image uploadée (prioritaire sur l'URL CDN)"),
        ),
        migrations.AddField(
            model_name='cosmeticproduct',
            name='video_file',
            field=models.FileField(blank=True, null=True, upload_to='products/videos/', verbose_name='Vidéo produit (MP4/WebM recommandé)'),
        ),
        migrations.AlterField(
            model_name='clothingproduct',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name="URL de l'image (CDN/Unsplash)"),
        ),
        migrations.AlterField(
            model_name='cosmeticproduct',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, verbose_name="URL de l'image (CDN/Unsplash)"),
        ),
    ]
