"""
Django settings for cleangirls_backend project.

Generated by 'django-admin startproject' using Django 4.2.30.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
import dj_database_url
from urllib.parse import quote

from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-col8l^)q&(d^dwcs43kz155y7vks0fz08dg7(vwh4s0q&^a7!^'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_CREDENTIALS = True

# --- AJOUTE CE BLOC ---
# Autorise les requêtes POST (comme le login) venant de ton domaine Render
CSRF_TRUSTED_ORIGINS = [
    "https://cleangirls-backend.onrender.com",
]
# On autorise ton nom de domaine en production ainsi que les accès locaux pour tes tests sur ton PC
ALLOWED_HOSTS = [
    'cleangirls-backend.onrender.com',
    'localhost',
    '127.0.0.1',
]

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'corsheaders',
    'core',
    'webpush',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'cleangirls_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'cleangirls_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases
if os.environ.get('RENDER'):
    # ==========================================
    # CONFIGURATION PRODUCTION (RENDER -> SUPABASE POOLER)
    # ==========================================
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'postgres',
            'USER': 'postgres.hpdrikswhoymbanuhhfc',
            'PASSWORD': 'yzC8U3M5#f-4f%Z',
            'HOST': 'aws-0-eu-west-1.pooler.supabase.com',  # <-- La bonne région (Irlande)
            'PORT': '6543',  # Port du pooler
            'CONN_MAX_AGE': 0, 
        }
    }
else:
    # ==========================================
    # CONFIGURATION LOCALE (WINDOWS -> MYSQL)
    # ==========================================
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.mysql',
            'NAME': 'cleangirls_db',
            'USER': 'root',
            'PASSWORD': '',
            'HOST': '127.0.0.1',
            'PORT': '3306',
            'OPTIONS': {
                'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            }
        }
    }
# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'fr-fr'

TIME_ZONE = 'Africa/Douala'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Dossier où collectstatic va rassembler tous tes fichiers statiques pour la prod
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Recommandé pour servir efficacement les fichiers statiques en prod
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files (uploaded images, videos)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'



REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'core.authentication.CsrfExemptSessionAuthentication',
    ],
}

# Email settings — Gmail SMTP avec App Password
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'alphonseessomba60@gmail.com'
EMAIL_HOST_PASSWORD = 'kbty stcu dspd fcwe'
DEFAULT_FROM_EMAIL = EMAIL_HOST_USER

# WebPush Notifications configuration (VAPID)
WEBPUSH_SETTINGS = {
    "VAPID_PUBLIC_KEY": "BLnkW4wZgw_C3rVYDPbwZLj8HOmmZqWaEKeT6k6jG88AJdUIN5J6UnX4bwBSOLl0HAOaQ1LND6aeeY8JA_ka2eM",
    "VAPID_PRIVATE_KEY": "AHhfXaAwYsg8CSstHqPPPBV6UAY_YsXZTj2Ug9V9tuI",
    "VAPID_ADMIN_EMAIL": EMAIL_HOST_USER,
}

